services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: kiwiburn
      POSTGRES_PASSWORD: kiwiburn
      POSTGRES_DB: voting_portal
    ports:
      - "6769:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
